spring:
  jpa:
    database: MYSQL
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/dendb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /