/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shoponline;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        ShopOnline classUnderTest = new ShopOnline();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
